In [2]:
import numpy as np

In [3]:
MyExampleArray = np.array([1,2,3,4,5])

In [4]:
MyExampleArray.size

5

Adding Arrays

In [5]:
A = np.array([[1,2],[3,4]])

In [6]:
B = np.array([[5,6],[7,8]])

In [7]:
np.add(A,B)

array([[ 6,  8],
       [10, 12]])

Multiplying Arrays

In [11]:
C = np.array([[1,2]])

In [14]:
D = np.array([[1],[1]])

In [15]:
np.matmul(C,D)

array([[3]])

Array Slicing [start:stop:step]

In [16]:
MyExampleArray[:4:]

array([1, 2, 3, 4])

In [17]:
MyExampleArray[1:4:2]

array([2, 4])

Reshape(.reshape(columns:rows))

In [18]:
x1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [19]:
x2 = x1.reshape(3,4)
print(x2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Copy

In [20]:
copy1 = MyExampleArray[0:4].copy()
print(copy1)

[1 2 3 4]


arange(start,stop,step,int)


In [24]:
x = np.arange(1,10) 
print(x)

[1 2 3 4 5 6 7 8 9]


In [26]:
x = np.arange(1.1,3.4,1)
print(x)

[1.1 2.1 3.1]


In [28]:
x = np.arange(1.1,100,25,int)
print(x)

[ 1 26 51 76]
